name: ton80
version: 0.1.0
description: Ton 80 is a benchmark suite for Dart.
environment:
  sdk: '>=1.2.0'
dependencies:
  path: '>=1.3.0 <1.4.0'
  quiver: '>=0.18.2 <0.19.0'
  args: '>=0.12.0 <0.13.0'
